<?xml version='1.0' encoding='utf-8'?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="camera">
    <!-- Used for fixing camera to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <origin xyz="0 0 1" rpy="0 0 0"/>
    <parent link="world"/>
    <child link="camera_link"/>
  </joint>

  <xacro:property name="height" value="0.1" />
  <xacro:property name="width" value="0.3" /> 
  <xacro:property name="depth" value="0.1" />  

  <link name="camera_link">
    <collision>
      <origin xyz="${depth/2} ${width/2} ${height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${depth} ${width} ${height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${depth/2} ${width/2} ${height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${depth} ${width} ${height}"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="${depth/2} ${width/2} ${height/2}" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <joint name="camera_optical_joint" type="fixed">
            <origin xyz="0 0 0" rpy="-1.5708 0 -1.5708"/>
            <parent link="camera_link"/>
            <child link="camera_optical"/>
        </joint>
  <link name="camera_optical"/>


  <xacro:property name="camera_name" value="camera" />
  <gazebo reference="camera_optical">
  <sensor name="camera" type="depth">
    <update_rate>20</update_rate>
    <camera>
      <horizontal_fov>1.047198</horizontal_fov>
      <image>
        <width>1280</width>
        <height>720</height>
        <format>B8G8R8</format>
      </image>
      <clip>
        <near>0.05</near>
        <far>3</far>
      </clip>
    </camera>
    <plugin name="rgbd_controller" filename="libgazebo_ros_openni_kinect.so">
      <baseline>0.2</baseline>
      <alwaysOn>true</alwaysOn>
      <updateRate>1.0</updateRate>
      <cameraName>${camera_name}_ir</cameraName>
      <imageTopicName>/${camera_name}/color/image_raw</imageTopicName>
      <cameraInfoTopicName>/${camera_name}/color/camera_info</cameraInfoTopicName>
      <depthImageTopicName>/${camera_name}/depth/image_raw</depthImageTopicName>
      <depthImageInfoTopicName>/${camera_name}/depth/camera_info</depthImageInfoTopicName>
      <pointCloudTopicName>/${camera_name}/depth/points</pointCloudTopicName>
      <frameName>camera_optical</frameName>
      <pointCloudCutoff>0.5</pointCloudCutoff>
      <pointCloudCutoffMax>3.0</pointCloudCutoffMax>
      <distortionK1>0.00000001</distortionK1>
      <distortionK2>0.00000001</distortionK2>
      <distortionK3>0.00000001</distortionK3>
      <distortionT1>0.00000001</distortionT1>
      <distortionT2>0.00000001</distortionT2>
      <CxPrime>0</CxPrime>
      <Cx>0</Cx>
      <Cy>0</Cy>
      <focalLength>0</focalLength>
      <hackBaseline>0</hackBaseline>
    </plugin>
  </sensor>
  </gazebo>
 
</robot>
